dataset: /pscratch/sd/a/atrupe/StFT/data/shallow-water/dataset.h5

patch_sizes:
  - [128, 128]
  - [64, 64]
  - [32, 32]
overlaps:
  - [1, 1]
  - [1, 1]
  - [1, 1]
vit_depth: [2, 2, 2]
modes:
  - [8, 8]
  - [8, 8]
  - [8, 8]

dim: 8
num_heads: 1
lr: 1.0e-4
max_epochs: 1
batchsize: 64
cond_time: 5
lift_channel: 8
act: gelu

save_path: /pscratch/sd/a/atrupe/StFT/experiments/test
save_every_n: 5
validate_every_n: 10

condition_blocks: true
use_snapshots: true
snapshot_length: 20

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
